from typing import Annotated

from langgraph.graph import MessagesState


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # analyst step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]

    # decision pipeline: single-pass, no debate rounds
    signal_decision: Annotated[str, "Directional call from the Signal Synthesizer"]
    critic_review: Annotated[str, "Critic Manager's verdict on whether the move is worth trading"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    final_trade_decision: Annotated[str, "Final decision (rating + SL/TP/size) made by the Risk Manager"]

    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
